---
- name: "Configure JournalD"
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/systemd/journald.conf"
    regexp: "{{ config.regexp }}"
    line: "{{ config.line }}"
  loop:
    - regexp: "^SystemMaxUse="
      line: "SystemMaxUse=100M"
    - regexp: "^SystemMaxFileSize="
      line: "SystemMaxFileSize=100M"
    - regexp: "^Compress="
      line: "Compress=yes"
  loop_control:
    loop_var: "config"
    label: "{{ config.regexp }}"
  notify: "Restart Journald"
