# Manage root user account
---
- name: "Update root User's Password"
  become: true
  ansible.builtin.user:
    name: "root"
    password: "{{ inventory.root_password }}"
  no_log: true

- name: "Set up root Users authorized keys"
  become: true
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ user.pubkey }}"
  when: "owner is defined and owner.users is defined and user.pubkey is defined and 'ADMIN' in user.roles"
  loop: "{{ owner.users | default([]) }}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"
  no_log: true

- name: "Configure Files"
  become: true
  ansible.builtin.copy:
    src: "{{ file.source }}"
    dest: "{{ file.destination }}"
    owner: "{{ file.owner | default('root') }}"
    group: "{{ file.group | default('root') }}"
    mode: "{{ file.mode | default('0644') }}"
  loop:
    - source: "bashrc"
      destination: "/root/.bashrc"
    - source: "bash_aliases"
      destination: "/root/.bash_aliases"
  loop_control:
    loop_var: file

- name: "Configure MTA"
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - src: "mail.rc.j2"
      dest: "/root/.mailrc"
      mode: "0440"
