---
dependency:
  name: galaxy
  options:
    requirements-file: collections.yml
driver:
  name: docker
platforms:
  - name: instance
    image: "docker.io/geerlingguy/docker-debian11-ansible"
    pre_build_image: true
    privileged: true
    command: "/lib/systemd/systemd"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - "/run"
      - "/tmp"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    links:
      hosts: inventory.yml
verifier:
  name: ansible
