---
name: "Molecule Test"

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  molecule:
    name: "Run Molecule Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Run Molecule Test"
        uses: gofrolist/molecule-action@v2
