---
name: "Lint & Test"

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  molecule:
    name: "Run Lint and Molecule Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Run ansible lint"
        uses: ansible/ansible-lint-action@main

      - name: "Run yaml lint"
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint

      - name: "Run Molecule Test"
        uses: gofrolist/molecule-action@v2
